package hk.ed.cpdb.util;

public enum APIResultCode {
	SUCCESS,
	SERVER_ERROR,
	DEVICE_ID_EMPTY,
	DEVICE_ID_EXISTED,
	DEVICE_ID_NOT_EXIST,
	DEVICE_ID_NOT_MAPPED,
	TRANSMISSION_ID_NOT_EXIST,
	TRANSMISSION_ENDED,
	INVALID_SESSION,
	INVALID_CREDENTIAL;
	
}
